const {PGlite}=require('@electric-sql/pglite');
const fs=require('fs'),assert=require('assert');
(async()=>{let db=new PGlite();await db.exec(`create role anon;create role authenticated;create schema auth;create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz);create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema auth to authenticated;grant execute on function auth.uid() to authenticated;`);await db.exec(fs.readFileSync(__dirname+'/../sql/001_schema.sql','utf8'));
const a='11111111-1111-4111-8111-111111111111',b='22222222-2222-4222-8222-222222222222',c='33333333-3333-4333-8333-333333333333';await db.query('insert into auth.users values ($1,$2,now()),($3,$4,now()),($5,$6,now())',[a,'a@example.test',b,'b@example.test',c,'c@example.test']);
async function as(u){await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[u]);await db.exec('set role authenticated')}
await as(a);let h=(await db.query("select public.create_household('Hogar') id")).rows[0].id;let seed={income:6000,expenses:[],products:[],list:[],paid:{}};await db.query('select * from public.save_household_state($1,0,$2)',[h,JSON.stringify(seed)]);await db.query('select public.set_household_invite($1,$2)',[h,'b@example.test']);await as(b);assert.equal((await db.query('select public.accept_household_invite() id')).rows[0].id,h);assert.equal((await db.query('select * from public.household_state')).rows.length,1);
await db.query('select * from public.save_household_state($1,1,$2)',[h,JSON.stringify(seed)]);
await as(a);await assert.rejects(()=>db.query('select * from public.save_household_state($1,1,$2)',[h,JSON.stringify(seed)]),/REVISION_CONFLICT/);await assert.rejects(()=>db.query('select public.set_household_invite($1,$2)',[h,'c@example.test']),/HOUSEHOLD_FULL/);await assert.rejects(()=>db.query('update public.household_state set revision=999'),/permission denied/);
await as(c);assert.equal((await db.query('select * from public.household_state')).rows.length,0);await assert.rejects(()=>db.query('select * from public.save_household_state($1,2,$2)',[h,JSON.stringify(seed)]),/FORBIDDEN/);await as(b);await assert.rejects(()=>db.query('select public.set_household_invite($1,$2)',[h,'c@example.test']),/FORBIDDEN/);assert.equal((await db.query('select count(*) n from public.household_audit')).rows[0].n,2);await db.exec('reset role');await db.exec(fs.readFileSync(__dirname+'/../sql/001_schema.sql','utf8'));console.log('PASS PostgreSQL: migration, idempotency, owner+member, RLS denies outsider, direct writes denied, max 2, audit, revision conflict.');await db.close()})().catch(e=>{console.error(e);process.exit(1)});
